// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpcjvvfzeqsimofhumjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwY2p2dmZ6ZXFzaW1vZmh1bWpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQzNDUzNjYsImV4cCI6MjA3OTkyMTM2Nn0.-Lc61KvwNehNZX8tzr6q3aY4-C0MiCTFZ1TIdogsEuY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});